version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name : portfolio_mysql
    restart : always
    environment:
    MYSQL_ROOT_PASSWORD: rootpassword
    MYSQL_DATABASE: portfolio_db
    MYSQL_USER: portfolio_user
    MYSQLI_PASSWORD : portfolio_pass
  ports:
    -"3306:3306"
  volumes:
    mysqli_data:/var/lib/mysql
  healthcheck:
    test: ["CMD","mysqliadmin","ping", "-h", "localhost"]
    timeout: 20s
    retries: 10
    